data:
  image: ubuntu:15.10
  volumes:
    - /var/lib/mysql
  command: "true"

mysql:
  restart: always
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: jamfsoftware
    MYSQL_USER: jamfsoftware
    MYSQL_PASSWORD: jamfsw03
  volumes_from:
    - data
  ports:
    - "3306:3306"

jss:
  restart: always
  image: my-jss
  links:
    - mysql
  ports:
    - "8443:8443"
